import img1 from "../assets/img1.png";
import img2 from "../assets/img2.png";
import img3 from "../assets/img3.png";

export const dessins = [
  { id: 1, photo: img1 },
  { id: 2, photo: img2 },
  { id: 3, photo: img3 },
];
export const Quizz = [
  {
    id: 1,
    topic: "Histoire",
    question: "En quelle année a commencé la Révolution française ?",
    choices: ["1776", "1789", "1804", "1848"],
    answer_index: 1,
    answer: "1789",
  },
  {
    id: 2,
    topic: "Histoire",
    question: "Quel événement est associé au 14 juillet ?",
    choices: [
      "La prise de la Bastille",
      "La proclamation de la République",
      "La bataille de Valmy",
      "La signature du traité de Verdun",
    ],
    answer_index: 0,
    answer: "La prise de la Bastille",
  },
  {
    id: 3,
    topic: "Histoire",
    question: "Qui était Napoléon Bonaparte avant de devenir Empereur ?",
    choices: [
      "Un officier révolutionnaire",
      "Un philosophe",
      "Un roi d'Espagne",
      "Un peintre",
    ],
    answer_index: 0,
    answer: "Un officier révolutionnaire",
  },
  {
    id: 4,
    topic: "Histoire",
    question: "Quel régime politique a succédé à la monarchie en 1792 ?",
    choices: ["L'Empire", "La République", "La Restauration", "La Commune"],
    answer_index: 1,
    answer: "La République",
  },
  {
    id: 5,
    topic: "Histoire",
    question:
      "Qui a dirigé la France libre pendant la Seconde Guerre mondiale ?",
    choices: [
      "Philippe Pétain",
      "Charles de Gaulle",
      "Georges Clemenceau",
      "Léon Blum",
    ],
    answer_index: 1,
    answer: "Charles de Gaulle",
  },
  {
    id: 6,
    topic: "Histoire",
    question:
      "Quel traité a mis fin à la Première Guerre mondiale pour l'Allemagne ?",
    choices: [
      "Traité de Rome",
      "Traité de Versailles",
      "Traité de Paris (1815)",
      "Traité de Tordesillas",
    ],
    answer_index: 1,
    answer: "Traité de Versailles",
  },
  {
    id: 7,
    topic: "Histoire",
    question:
      "Qui fut un des principaux chefs de gouvernement au début de la IIIe République ?",
    choices: [
      "Adolphe Thiers",
      "Jules Ferry",
      "Georges Clemenceau",
      "Léon Gambetta",
    ],
    answer_index: 0,
    answer: "Adolphe Thiers",
  },
  {
    id: 8,
    topic: "Histoire",
    question: "Quel roi fut guillotiné pendant la Révolution française ?",
    choices: ["Louis XVI", "Louis XVIII", "Charles X", "Louis-Philippe"],
    answer_index: 0,
    answer: "Louis XVI",
  },
  {
    id: 9,
    topic: "Histoire",
    question:
      "Quelle révolution a instauré le suffrage universel masculin en France (première fois) ?",
    choices: [
      "Révolution de 1830",
      "Révolution de 1848",
      "Révolution de 1870",
      "Mai 1968",
    ],
    answer_index: 1,
    answer: "Révolution de 1848",
  },
  {
    id: 10,
    topic: "Histoire",
    question:
      "Quel est le nom du système de coopération entre puissances européennes après le Congrès de Vienne (1815) ?",
    choices: ["Restauration", "Concert européen", "Belle Époque", "République"],
    answer_index: 1,
    answer: "Concert européen",
  },
  {
    id: 11,
    topic: "Histoire",
    question: "Qui a proclamé la IIIe République en France ?",
    choices: [
      "Adolphe Thiers",
      "Léon Gambetta",
      "Charles de Gaulle",
      "Napoléon III",
    ],
    answer_index: 1,
    answer: "Léon Gambetta",
  },
  {
    id: 12,
    topic: "Histoire",
    question: "Quel événement marque la fin du régime de Vichy ?",
    choices: [
      "L'armistice de 1940",
      "La Libération de la France",
      "La signature du pacte germano-soviétique",
      "La bataille de France",
    ],
    answer_index: 1,
    answer: "La Libération de la France",
  },
  {
    id: 13,
    topic: "Histoire",
    question: "Quel bâtiment a été pris d'assaut le 14 juillet 1789 ?",
    choices: ["La Bastille", "Le Louvre", "Le Panthéon", "Le Palais-Royal"],
    answer_index: 0,
    answer: "La Bastille",
  },
  {
    id: 14,
    topic: "Histoire",
    question:
      "Qui était le chef de la diplomatie française lors de la signature du traité de Versailles (1919) ?",
    choices: [
      "Georges Clemenceau",
      "Raymond Poincaré",
      "Aristide Briand",
      "Léon Blum",
    ],
    answer_index: 0,
    answer: "Georges Clemenceau",
  },
  {
    id: 15,
    topic: "Histoire",
    question: "Quand Napoléon se fit-il sacrer Empereur ?",
    choices: ["1804", "1799", "1815", "1800"],
    answer_index: 0,
    answer: "1804",
  },
  {
    id: 16,
    topic: "Histoire",
    question: "Quel mouvement social français est associé à 1968 ?",
    choices: [
      "La Commune",
      "La Révolution de 1848",
      "Mai 68",
      "La Restauration",
    ],
    answer_index: 2,
    answer: "Mai 68",
  },
  {
    id: 17,
    topic: "Histoire",
    question: "Quel roi mit fin à l'Ancien Régime après la Révolution ?",
    choices: ["Louis XVI", "Louis XV", "Louis-Philippe", "Henri IV"],
    answer_index: 0,
    answer: "Louis XVI",
  },
  {
    id: 18,
    topic: "Histoire",
    question:
      "Quel programme a inspiré les réformes sociales après la Libération en 1944 ?",
    choices: [
      "Le Programme du Conseil national de la Résistance",
      "Le plan Marshall",
      "Le New Deal",
      "Le Plan Monnet",
    ],
    answer_index: 0,
    answer: "Le Programme du Conseil national de la Résistance",
  },
  {
    id: 19,
    topic: "Histoire",
    question:
      "Quel conflit a opposé la France à l'Allemagne entre 1870 et 1871 ?",
    choices: [
      "La Première Guerre mondiale",
      "La guerre franco-prussienne",
      "La guerre d'Indochine",
      "La guerre de Cent Ans",
    ],
    answer_index: 1,
    answer: "La guerre franco-prussienne",
  },
  {
    id: 20,
    topic: "Histoire",
    question:
      "Qui fut le président français immédiatement après la Libération (Provisoire) ?",
    choices: [
      "Vincent Auriol",
      "Charles de Gaulle",
      "Georges Pompidou",
      "René Coty",
    ],
    answer_index: 1,
    answer: "Charles de Gaulle",
  },
  {
    id: 21,
    topic: "Histoire",
    question:
      "Quelle bataille de 732 est célèbre pour avoir arrêté l'expansion musulmane en Europe occidentale ?",
    choices: [
      "Bataille de Hastings",
      "Bataille de Poitiers (Tours)",
      "Bataille d'Azincourt",
      "Bataille de Marignan",
    ],
    answer_index: 1,
    answer: "Bataille de Poitiers (Tours)",
  },
  {
    id: 22,
    topic: "Histoire",
    question:
      "Quel roi a fondé la dynastie carolingienne célèbre par Charlemagne ?",
    choices: ["Clovis", "Pépin le Bref", "Hugues Capet", "Louis IX"],
    answer_index: 1,
    answer: "Pépin le Bref",
  },
  {
    id: 23,
    topic: "Histoire",
    question:
      "Qui fut le principal artisan de la Révolution industrielle en France au XIXe siècle (figure politique) ?",
    choices: [
      "Jules Ferry",
      "Adolphe Thiers",
      "Napoléon III",
      "Pierre Mendès France",
    ],
    answer_index: 2,
    answer: "Napoléon III",
  },
  {
    id: 24,
    topic: "Histoire",
    question:
      "Quel célèbre code civil français a été promulgué sous Napoléon ?",
    choices: [
      "Code pénal",
      "Code civil (Code Napoléon)",
      "Code du travail",
      "Code maritime",
    ],
    answer_index: 1,
    answer: "Code civil (Code Napoléon)",
  },
  {
    id: 25,
    topic: "Histoire",
    question: "Quel roi fit construire le château de Versailles ?",
    choices: ["Louis XVI", "Louis XIV", "François Ier", "Henri IV"],
    answer_index: 1,
    answer: "Louis XIV",
  },
  {
    id: 26,
    topic: "Histoire",
    question: "Quel est le nom du parlement français sous l'Ancien Régime ?",
    choices: [
      "Les États généraux",
      "Le Sénat",
      "L'Assemblée nationale",
      "Le Conseil d'État",
    ],
    answer_index: 0,
    answer: "Les États généraux",
  },
  {
    id: 27,
    topic: "Histoire",
    question: "Qui était Jeanne d'Arc ?",
    choices: [
      "Une reine",
      "Une sainte et chef militaire",
      "Une aristocrate anglaise",
      "Une philosophe",
    ],
    answer_index: 1,
    answer: "Une sainte et chef militaire",
  },
  {
    id: 28,
    topic: "Histoire",
    question:
      "En quelle année la France a-t-elle aboli l'esclavage pour la première fois ?",
    choices: ["1794", "1848", "1815", "1945"],
    answer_index: 0,
    answer: "1794",
  },
  {
    id: 29,
    topic: "Histoire",
    question:
      "Quel grand roi humaniste fit construire le château de Chambord ?",
    choices: ["François Ier", "Louis XI", "Henri II", "Charles VII"],
    answer_index: 0,
    answer: "François Ier",
  },
  {
    id: 30,
    topic: "Histoire",
    question:
      "Quelle ville fut le siège du gouvernement de Vichy de 1940 à 1944 ?",
    choices: ["Paris", "Bordeaux", "Vichy", "Lyon"],
    answer_index: 2,
    answer: "Vichy",
  },
  {
    id: 31,
    topic: "Histoire",
    question:
      "Quelle conférence a partagé l'Europe en sphères d'influence après la Seconde Guerre mondiale ?",
    choices: [
      "Traité de Versailles",
      "Conférence de Yalta",
      "Traité de Trianon",
      "Traité de Sèvres",
    ],
    answer_index: 1,
    answer: "Conférence de Yalta",
  },
  {
    id: 32,
    topic: "Histoire",
    question: "Qui fut le roi fondateur de la dynastie capétienne ?",
    choices: ["Clovis", "Hugues Capet", "Charlemagne", "Louis IX"],
    answer_index: 1,
    answer: "Hugues Capet",
  },
  {
    id: 33,
    topic: "Histoire",
    question: "Quel siècle correspond à la Révolution française ?",
    choices: ["XVIIIe siècle", "XIXe siècle", "XVIIe siècle", "XXe siècle"],
    answer_index: 0,
    answer: "XVIIIe siècle",
  },
  {
    id: 34,
    topic: "Histoire",
    question:
      "Quel événement a marqué la fin de la monarchie en France en 1848 ?",
    choices: [
      "La chute de Napoléon III",
      "La proclamation de la Seconde République",
      "La Restauration",
      "Le coup d'État de 1851",
    ],
    answer_index: 1,
    answer: "La proclamation de la Seconde République",
  },
  {
    id: 35,
    topic: "Histoire",
    question:
      "Quelle guerre coloniale majeure a opposé la France au Viet Minh ?",
    choices: [
      "La guerre d'Algérie",
      "La guerre d'Indochine",
      "La guerre du Golfe",
      "La guerre d'Espagne",
    ],
    answer_index: 1,
    answer: "La guerre d'Indochine",
  },
  {
    id: 36,
    topic: "Valeurs républicaines",
    question: "Quelle est la devise de la République française ?",
    choices: [
      "Liberté, unité, fraternité",
      "Liberté, égalité, fraternité",
      "Unité, égalité, solidarité",
      "Travail, famille, patrie",
    ],
    answer_index: 1,
    answer: "Liberté, égalité, fraternité",
  },
  {
    id: 37,
    topic: "Valeurs républicaines",
    question: "Que signifie la laïcité en France ?",
    choices: [
      "Séparation de l'Église et de l'État",
      "Religion d'État obligatoire",
      "Union entre l'Église et l'État",
      "Pratique religieuse obligatoire à l'école",
    ],
    answer_index: 0,
    answer: "Séparation de l'Église et de l'État",
  },
  {
    id: 38,
    topic: "Valeurs républicaines",
    question:
      "Quel principe interdit toute discrimination fondée sur l'origine, le sexe, la religion ?",
    choices: ["Laïcité", "Liberté", "Égalité", "Souveraineté"],
    answer_index: 2,
    answer: "Égalité",
  },
  {
    id: 39,
    topic: "Valeurs républicaines",
    question: "Quel droit fondamental permet de s'exprimer librement ?",
    choices: [
      "Le droit à l'éducation",
      "La liberté d'expression",
      "Le droit à la propriété",
      "La liberté de culte",
    ],
    answer_index: 1,
    answer: "La liberté d'expression",
  },
  {
    id: 40,
    topic: "Valeurs républicaines",
    question: "Qu'est-ce que la fraternité selon les valeurs républicaines ?",
    choices: [
      "L'entraide et la solidarité entre citoyens",
      "La supériorité de l'État",
      "L'obligation de religion",
      "La neutralité de la presse",
    ],
    answer_index: 0,
    answer: "L'entraide et la solidarité entre citoyens",
  },
  {
    id: 41,
    topic: "Valeurs républicaines",
    question: "Quel droit protège la vie privée des citoyens ?",
    choices: [
      "Le droit d'asile",
      "Le droit au respect de la vie privée",
      "La liberté d'expression",
      "Le droit de grève",
    ],
    answer_index: 1,
    answer: "Le droit au respect de la vie privée",
  },
  {
    id: 42,
    topic: "Valeurs républicaines",
    question: "Qui bénéficie des droits et devoirs en France ?",
    choices: [
      "Seulement les Français nés en France",
      "Tous les citoyens français",
      "Seulement les fonctionnaires",
      "Les étrangers seulement",
    ],
    answer_index: 1,
    answer: "Tous les citoyens français",
  },
  {
    id: 43,
    topic: "Valeurs républicaines",
    question: "Qu'est-ce que la neutralité de l'État ?",
    choices: [
      "L'État impose une religion",
      "L'État ne favorise aucune religion",
      "L'État finit toutes les pratiques religieuses",
      "L'État contrôle les écoles privées",
    ],
    answer_index: 1,
    answer: "L'État ne favorise aucune religion",
  },
  {
    id: 44,
    topic: "Valeurs républicaines",
    question: "Quel est le devoir civique important lors des élections ?",
    choices: [
      "Payer des impôts",
      "Voter",
      "Servir dans l'armée",
      "Travailler pour un parti politique",
    ],
    answer_index: 1,
    answer: "Voter",
  },
  {
    id: 45,
    topic: "Valeurs républicaines",
    question: "Qu'est-ce que la liberté de conscience ?",
    choices: [
      "Imposer une croyance",
      "Ne pas être obligé d'adhérer à une religion",
      "Obliger l'État à fournir une religion",
      "La liberté de porter des uniformes religieux à l'école primaire",
    ],
    answer_index: 1,
    answer: "Ne pas être obligé d'adhérer à une religion",
  },
  {
    id: 46,
    topic: "Valeurs républicaines",
    question: "Quel principe garantit que la loi est la même pour tous ?",
    choices: [
      "L'inégalité devant la loi",
      "L'égalité devant la loi",
      "Le privilège d'origine noble",
      "L'impunité",
    ],
    answer_index: 1,
    answer: "L'égalité devant la loi",
  },
  {
    id: 47,
    topic: "Valeurs républicaines",
    question: "Quelle liberté concerne la presse ?",
    choices: [
      "Liberté d'entreprendre",
      "Liberté de la presse",
      "Liberté de culte",
      "Liberté scolaire",
    ],
    answer_index: 1,
    answer: "Liberté de la presse",
  },
  {
    id: 48,
    topic: "Valeurs républicaines",
    question:
      "Quel principe interdit la torture et les traitements inhumains ?",
    choices: [
      "La dignité de la personne humaine",
      "La souveraineté nationale",
      "La laïcité",
      "La subsidiarité",
    ],
    answer_index: 0,
    answer: "La dignité de la personne humaine",
  },
  {
    id: 49,
    topic: "Institutions",
    question: "Quel est le rôle du Président de la République ?",
    choices: [
      "Présider le Parlement",
      "Garantir le respect de la Constitution et représenter la nation",
      "Rédiger les lois seul",
      "Présider la Cour de cassation",
    ],
    answer_index: 1,
    answer: "Garantir le respect de la Constitution et représenter la nation",
  },
  {
    id: 50,
    topic: "Institutions",
    question: "Combien de chambres compose le Parlement français ?",
    choices: [
      "Une seule",
      "Deux (Assemblée nationale et Sénat)",
      "Trois",
      "Quatre",
    ],
    answer_index: 1,
    answer: "Deux (Assemblée nationale et Sénat)",
  },
  {
    id: 51,
    topic: "Institutions",
    question: "Qui vote les lois en France ?",
    choices: [
      "Le Conseil constitutionnel",
      "Le Gouvernement seul",
      "Le Parlement (députés et sénateurs)",
      "Le Président seul",
    ],
    answer_index: 2,
    answer: "Le Parlement (députés et sénateurs)",
  },
  {
    id: 52,
    topic: "Institutions",
    question: "Quel est le rôle du Premier ministre ?",
    choices: [
      "Exécuter les décisions du Président sans responsabilité",
      "Diriger l'action du Gouvernement et coordonner les ministères",
      "Présider le Sénat",
      "Contrôler la justice",
    ],
    answer_index: 1,
    answer: "Diriger l'action du Gouvernement et coordonner les ministères",
  },
  {
    id: 53,
    topic: "Institutions",
    question: "Quelle institution contrôle la constitutionnalité des lois ?",
    choices: [
      "Le Conseil d'État",
      "Le Conseil constitutionnel",
      "La Cour des comptes",
      "L'Assemblée nationale",
    ],
    answer_index: 1,
    answer: "Le Conseil constitutionnel",
  },
  {
    id: 54,
    topic: "Institutions",
    question: "Quel est le rôle du préfet en France ?",
    choices: [
      "Représenter l'État dans un département",
      "Diriger le conseil régional",
      "Gérer la politique européenne",
      "Nommer le Président",
    ],
    answer_index: 0,
    answer: "Représenter l'État dans un département",
  },
  {
    id: 55,
    topic: "Institutions",
    question:
      "Quelle institution conseille le Gouvernement sur les projets de loi et gère la juridiction administrative ?",
    choices: [
      "La Cour de cassation",
      "Le Conseil d'État",
      "Le Conseil constitutionnel",
      "La Cour européenne des droits de l'homme",
    ],
    answer_index: 1,
    answer: "Le Conseil d'État",
  },
  {
    id: 56,
    topic: "Institutions",
    question: "Quel est le rôle de la Cour de cassation ?",
    choices: [
      "Jugement en première instance des délits",
      "Vérifier la conformité des décisions de justice au droit",
      "Voter les lois",
      "Gérer les finances publiques",
    ],
    answer_index: 1,
    answer: "Vérifier la conformité des décisions de justice au droit",
  },
  {
    id: 57,
    topic: "Institutions",
    question: "Qui peut proposer des lois en France ?",
    choices: [
      "Seul le Président",
      "Le Gouvernement et les membres du Parlement",
      "Le Conseil constitutionnel",
      "Les préfets",
    ],
    answer_index: 1,
    answer: "Le Gouvernement et les membres du Parlement",
  },
  {
    id: 58,
    topic: "Institutions",
    question: "Qu'est-ce qu'un décret ?",
    choices: [
      "Une proposition de loi",
      "Un acte réglementaire pris par le Gouvernement",
      "Une décision du Parlement",
      "Une loi votée par référendum",
    ],
    answer_index: 1,
    answer: "Un acte réglementaire pris par le Gouvernement",
  },
  {
    id: 59,
    topic: "Institutions",
    question: "Quel est l'âge minimum pour être élu député en France ?",
    choices: ["18 ans", "21 ans", "25 ans", "30 ans"],
    answer_index: 0,
    answer: "18 ans",
  },
  {
    id: 60,
    topic: "Institutions",
    question: "Quel est l'organe chargé de contrôler le budget de l'État ?",
    choices: [
      "La Cour des comptes",
      "Le Conseil constitutionnel",
      "Le Sénat",
      "Le Conseil d'État",
    ],
    answer_index: 0,
    answer: "La Cour des comptes",
  },
  {
    id: 61,
    topic: "Politique",
    question: "Qu'est-ce qu'un gouvernement de coalition ?",
    choices: [
      "Un gouvernement formé par un seul parti",
      "Un gouvernement soutenu par des partis différents en alliance",
      "Un conseil municipal",
      "Un gouvernement d'un chef militaire",
    ],
    answer_index: 1,
    answer: "Un gouvernement soutenu par des partis différents en alliance",
  },
  {
    id: 62,
    topic: "Politique",
    question:
      "Quel système électoral est utilisé pour l'élection présidentielle en France ?",
    choices: [
      "Scrutin proportionnel",
      "Scrutin uninominal à deux tours",
      "Scrutin plurinominal",
      "Scrutin majoritaire à un tour",
    ],
    answer_index: 1,
    answer: "Scrutin uninominal à deux tours",
  },
  {
    id: 63,
    topic: "Politique",
    question: "Qu'est-ce qu'un parti politique ?",
    choices: [
      "Un groupe d'individus partageant des idées politiques et cherchant des mandats",
      "Une ONG humanitaire",
      "Une entreprise privée",
      "Une institution judiciaire",
    ],
    answer_index: 0,
    answer:
      "Un groupe d'individus partageant des idées politiques et cherchant des mandats",
  },
  {
    id: 64,
    topic: "Politique",
    question: "Quel est le rôle d'un député ?",
    choices: [
      "Rédiger et voter les lois",
      "Appliquer les lois",
      "Contrôler les tribunaux",
      "Nommer les ministres",
    ],
    answer_index: 0,
    answer: "Rédiger et voter les lois",
  },
  {
    id: 65,
    topic: "Politique",
    question: "Qu'est-ce que la motion de censure ?",
    choices: [
      "Un vote qui destitue le Président",
      "Un vote à l'Assemblée nationale qui peut renverser le Gouvernement",
      "Une loi votée par le Sénat",
      "Un type de référendum local",
    ],
    answer_index: 1,
    answer:
      "Un vote à l'Assemblée nationale qui peut renverser le Gouvernement",
  },
  {
    id: 66,
    topic: "Politique",
    question: "Quel organisme organise les élections en France ?",
    choices: [
      "Le Conseil constitutionnel",
      "La commission européenne",
      "Le ministère de l'Intérieur",
      "Le Sénat",
    ],
    answer_index: 2,
    answer: "Le ministère de l'Intérieur",
  },
  {
    id: 67,
    topic: "Politique",
    question: "Que signifie le terme « mandat » en politique ?",
    choices: [
      "Un document administratif",
      "La durée pendant laquelle une personne exerce une fonction élue",
      "Un parti politique",
      "Un impôt",
    ],
    answer_index: 1,
    answer: "La durée pendant laquelle une personne exerce une fonction élue",
  },
  {
    id: 68,
    topic: "Politique",
    question: "Quel est l'objectif d'un programme politique ?",
    choices: [
      "Organiser des élections",
      "Présenter les propositions d'un candidat ou d'un parti pour gouverner",
      "Contrôler la justice",
      "Gérer les finances municipales",
    ],
    answer_index: 1,
    answer:
      "Présenter les propositions d'un candidat ou d'un parti pour gouverner",
  },
  {
    id: 69,
    topic: "Politique",
    question: "Qu'est-ce que le référendum ?",
    choices: [
      "Une loi votée par le Parlement",
      "Une consultation directe des citoyens sur une question",
      "Un type de budget",
      "Une procédure judiciaire",
    ],
    answer_index: 1,
    answer: "Une consultation directe des citoyens sur une question",
  },
  {
    id: 70,
    topic: "Géographie",
    question: "Quelle est la capitale de la France ?",
    choices: ["Marseille", "Lyon", "Paris", "Bordeaux"],
    answer_index: 2,
    answer: "Paris",
  },
  {
    id: 71,
    topic: "Géographie",
    question: "Quel est le plus long fleuve de France ?",
    choices: ["La Loire", "La Seine", "Le Rhône", "La Garonne"],
    answer_index: 0,
    answer: "La Loire",
  },
  {
    id: 72,
    topic: "Géographie",
    question: "Dans quelle région se trouve le Mont-Saint-Michel ?",
    choices: [
      "Normandie",
      "Bretagne",
      "Occitanie",
      "Provence-Alpes-Côte d'Azur",
    ],
    answer_index: 0,
    answer: "Normandie",
  },
  {
    id: 73,
    topic: "Géographie",
    question: "Quel massif montagneux sépare la France de l'Espagne ?",
    choices: ["Les Alpes", "Les Pyrénées", "Le Massif central", "Le Jura"],
    answer_index: 1,
    answer: "Les Pyrénées",
  },
  {
    id: 74,
    topic: "Géographie",
    question: "Quelle grande ville est située sur la Garonne ?",
    choices: ["Lille", "Toulouse", "Bordeaux", "Nice"],
    answer_index: 2,
    answer: "Bordeaux",
  },
  {
    id: 75,
    topic: "Géographie",
    question: "Quel est le département le plus peuplé de France (métropole) ?",
    choices: ["Bouches-du-Rhône", "Nord", "Paris (75)", "Rhône"],
    answer_index: 2,
    answer: "Paris (75)",
  },
  {
    id: 76,
    topic: "Géographie",
    question: "Quelle chaîne de montagnes contient le Mont-Blanc ?",
    choices: ["Les Pyrénées", "Les Alpes", "Le Massif central", "Le Jura"],
    answer_index: 1,
    answer: "Les Alpes",
  },
  {
    id: 77,
    topic: "Géographie",
    question: "Quelle région est connue pour ses vignobles de Bordeaux ?",
    choices: ["Nouvelle-Aquitaine", "Bretagne", "Hauts-de-France", "Normandie"],
    answer_index: 0,
    answer: "Nouvelle-Aquitaine",
  },
  {
    id: 78,
    topic: "Géographie",
    question:
      "Quelle île française est située en Méditerranée et célèbre pour sa culture distincte ?",
    choices: ["La Corse", "La Guadeloupe", "La Réunion", "Majorque"],
    answer_index: 0,
    answer: "La Corse",
  },
  {
    id: 79,
    topic: "Géographie",
    question:
      "Quel est l'océan qui borde la côte ouest de la France métropolitaine ?",
    choices: [
      "Océan Indien",
      "Océan Pacifique",
      "Océan Atlantique",
      "Mer Méditerranée",
    ],
    answer_index: 2,
    answer: "Océan Atlantique",
  },
  {
    id: 80,
    topic: "Géographie",
    question: "Quel fleuve traverse Paris ?",
    choices: ["La Loire", "La Seine", "Le Rhône", "La Garonne"],
    answer_index: 1,
    answer: "La Seine",
  },
  {
    id: 81,
    topic: "Géographie",
    question:
      "Quelle ville est la préfecture de la région Auvergne-Rhône-Alpes ?",
    choices: ["Lyon", "Clermont-Ferrand", "Grenoble", "Saint-Étienne"],
    answer_index: 0,
    answer: "Lyon",
  },
  {
    id: 82,
    topic: "Géographie",
    question:
      "Quelle grande plaine agricole se situe au nord-est de la France ?",
    choices: ["La Beauce", "La Provence", "Le Pays Basque", "La Corse"],
    answer_index: 0,
    answer: "La Beauce",
  },
  {
    id: 83,
    topic: "Géographie",
    question: "Quel est le principal port français sur la Manche ?",
    choices: ["Marseille", "Le Havre", "Toulon", "Brest"],
    answer_index: 1,
    answer: "Le Havre",
  },
  {
    id: 84,
    topic: "Culture",
    question: "Quel auteur français a écrit « Les Misérables » ?",
    choices: [
      "Honoré de Balzac",
      "Victor Hugo",
      "Émile Zola",
      "Gustave Flaubert",
    ],
    answer_index: 1,
    answer: "Victor Hugo",
  },
  {
    id: 85,
    topic: "Culture",
    question:
      "Quel peintre impressionniste a peint « Impression, soleil levant » ?",
    choices: [
      "Édouard Manet",
      "Claude Monet",
      "Paul Cézanne",
      "Pierre-Auguste Renoir",
    ],
    answer_index: 1,
    answer: "Claude Monet",
  },
  {
    id: 86,
    topic: "Culture",
    question:
      "Quel compositeur français a écrit « La Mer » (époque impressionniste) ?",
    choices: [
      "Maurice Ravel",
      "Claude Debussy",
      "Camille Saint-Saëns",
      "Hector Berlioz",
    ],
    answer_index: 1,
    answer: "Claude Debussy",
  },
  {
    id: 87,
    topic: "Culture",
    question: "Quel est le musée le plus visité de France situé à Paris ?",
    choices: [
      "Musée d'Orsay",
      "Musée du Louvre",
      "Centre Pompidou",
      "Musée Rodin",
    ],
    answer_index: 1,
    answer: "Musée du Louvre",
  },
  {
    id: 88,
    topic: "Culture",
    question: "Quel monument est une grande cathédrale gothique de Paris ?",
    choices: [
      "Sainte-Chapelle",
      "Notre-Dame de Paris",
      "Basilique du Sacré-Cœur",
      "Saint-Sulpice",
    ],
    answer_index: 1,
    answer: "Notre-Dame de Paris",
  },
  {
    id: 89,
    topic: "Culture",
    question:
      "Quel style architectural est caractéristique des cathédrales du Moyen Âge en France ?",
    choices: ["Baroque", "Gothique", "Renaissance", "Classique"],
    answer_index: 1,
    answer: "Gothique",
  },
  {
    id: 90,
    topic: "Culture",
    question:
      "Quel est le plat traditionnel composé de pommes de terre et de fromage râpé originaire des Alpes ?",
    choices: ["La bouillabaisse", "La raclette", "Le cassoulet", "La fondue"],
    answer_index: 3,
    answer: "La fondue",
  },
  {
    id: 91,
    topic: "Culture",
    question:
      "Quelle boisson est traditionnellement associée à la région de Champagne ?",
    choices: ["Vin de Bordeaux", "Champagne (vin mousseux)", "Pastis", "Cidre"],
    answer_index: 1,
    answer: "Champagne (vin mousseux)",
  },
  {
    id: 92,
    topic: "Culture",
    question:
      "Quel écrivain français a reçu le prix Nobel de littérature en 1957 ?",
    choices: [
      "Albert Camus",
      "Jean-Paul Sartre",
      "Marcel Proust",
      "André Gide",
    ],
    answer_index: 0,
    answer: "Albert Camus",
  },
  {
    id: 93,
    topic: "Patrimoine",
    question:
      "Quel château est emblématique de la Loire et de la Renaissance ?",
    choices: [
      "Château de Versailles",
      "Château de Chambord",
      "Château de Fontainebleau",
      "Château d'If",
    ],
    answer_index: 1,
    answer: "Château de Chambord",
  },
  {
    id: 94,
    topic: "Patrimoine",
    question:
      "Quel site est classé au patrimoine mondial de l'UNESCO en Normandie connu pour le débarquement de 1944 ?",
    choices: [
      "Mont-Saint-Michel",
      "Les plages du Débarquement (D-Day)",
      "Château de Caen",
      "Abbaye du Mont",
    ],
    answer_index: 1,
    answer: "Les plages du Débarquement (D-Day)",
  },
  {
    id: 95,
    topic: "Patrimoine",
    question:
      "Quel palais est associé à la monarchie absolue et aux fêtes de la cour ?",
    choices: [
      "Palais du Luxembourg",
      "Palais Bourbon",
      "Château de Versailles",
      "Palais Garnier",
    ],
    answer_index: 2,
    answer: "Château de Versailles",
  },
  {
    id: 96,
    topic: "Patrimoine",
    question:
      "Quelle ville est célèbre pour son patrimoine médiéval et sa cathédrale en Bourgogne ?",
    choices: ["Dijon", "Avignon", "Bordeaux", "Amiens"],
    answer_index: 0,
    answer: "Dijon",
  },
  {
    id: 97,
    topic: "Patrimoine",
    question:
      "Quel monument parisien a été construit comme tour d'exposition pour 1889 ?",
    choices: [
      "Arc de Triomphe",
      "Tour Eiffel",
      "Panthéon",
      "Grande Arche de la Défense",
    ],
    answer_index: 1,
    answer: "Tour Eiffel",
  },
  {
    id: 98,
    topic: "Patrimoine",
    question:
      "Quelle région française est célèbre pour ses calanques et son littoral méditerranéen ?",
    choices: [
      "Bretagne",
      "Provence-Alpes-Côte d'Azur",
      "Normandie",
      "Grand Est",
    ],
    answer_index: 1,
    answer: "Provence-Alpes-Côte d'Azur",
  },
  {
    id: 99,
    topic: "Patrimoine",
    question: "Quel est le nom du célèbre pont médiéval à Avignon ?",
    choices: [
      "Pont Neuf",
      "Pont d'Avignon (Pont Saint-Bénézet)",
      "Pont du Gard",
      "Pont Alexandre III",
    ],
    answer_index: 1,
    answer: "Pont d'Avignon (Pont Saint-Bénézet)",
  },
  {
    id: 100,
    topic: "Patrimoine",
    question:
      "Quel est le lieu de sépulture des grands personnages français à Paris ?",
    choices: [
      "Le Panthéon",
      "La Basilique du Sacré-Cœur",
      "La Madeleine",
      "Le Père-Lachaise",
    ],
    answer_index: 0,
    answer: "Le Panthéon",
  },
  {
    id: 101,
    topic: "Histoire",
    question:
      "Quel était le nom de la peste qui frappa l'Europe au XIVe siècle et affecta la France ?",
    choices: [
      "La peste antonine",
      "La peste noire",
      "La peste de Justinien",
      "La variole",
    ],
    answer_index: 1,
    answer: "La peste noire",
  },
  {
    id: 102,
    topic: "Histoire",
    question:
      "Quel commandant allié dirigeait les forces du débarquement en Normandie en 1944 ?",
    choices: [
      "Philippe Pétain",
      "Dwight D. Eisenhower",
      "Charles de Gaulle",
      "Bernard Law Montgomery",
    ],
    answer_index: 1,
    answer: "Dwight D. Eisenhower",
  },
  {
    id: 103,
    topic: "Histoire",
    question: "Quel roi français fut surnommé « le Roi Soleil » ?",
    choices: ["Louis XIV", "François Ier", "Henri IV", "Louis XIII"],
    answer_index: 0,
    answer: "Louis XIV",
  },
  {
    id: 104,
    topic: "Valeurs républicaines",
    question:
      "Que protège la Déclaration des droits de l'homme et du citoyen (1789) ?",
    choices: [
      "Les privilèges de la noblesse",
      "Les droits fondamentaux et les libertés individuelles",
      "La monarchie absolue",
      "Les corporations d'artisans",
    ],
    answer_index: 1,
    answer: "Les droits fondamentaux et les libertés individuelles",
  },
  {
    id: 105,
    topic: "Institutions",
    question:
      "Quelle institution statue sur la compatibilité des lois avec la Constitution avant leur promulgation (saisine) ?",
    choices: [
      "La Cour de cassation",
      "Le Conseil constitutionnel",
      "Le Conseil d'État",
      "La Cour européenne des droits de l'homme",
    ],
    answer_index: 1,
    answer: "Le Conseil constitutionnel",
  },
  {
    id: 106,
    topic: "Politique",
    question: "Que désigne le terme « alternance » en politique française ?",
    choices: [
      "La rotation annuelle des préfets",
      "Le changement de majorité politique au pouvoir",
      "Le partage du budget",
      "L'élection d'un maire",
    ],
    answer_index: 1,
    answer: "Le changement de majorité politique au pouvoir",
  },
  {
    id: 107,
    topic: "Géographie",
    question:
      "Quel est le nom de la chaîne de montagnes au centre de la France ?",
    choices: ["Les Alpes", "Le Massif central", "Le Jura", "Les Vosges"],
    answer_index: 1,
    answer: "Le Massif central",
  },
  {
    id: 108,
    topic: "Culture",
    question: "Quel poète français a écrit « Le Bateau ivre » ?",
    choices: ["Arthur Rimbaud", "Paul Verlaine", "Victor Hugo", "Stendhal"],
    answer_index: 0,
    answer: "Arthur Rimbaud",
  },
  {
    id: 109,
    topic: "Patrimoine",
    question:
      "Quel aqueduc romain près de Nîmes est un chef-d'œuvre d'ingénierie antique ?",
    choices: ["Pont du Gard", "Aqua Claudia", "Pont d'Avignon", "Pont Neuf"],
    answer_index: 0,
    answer: "Pont du Gard",
  },
  {
    id: 110,
    topic: "Histoire",
    question:
      "Quel événement international a largement façonné la politique française au XXe siècle ?",
    choices: [
      "La découverte de l'Amérique",
      "Les guerres mondiales",
      "La bataille de Waterloo",
      "La Réforme protestante",
    ],
    answer_index: 1,
    answer: "Les guerres mondiales",
  },
  {
    id: 111,
    topic: "Valeurs républicaines",
    question: "Quel principe protège la liberté religieuse en France ?",
    choices: [
      "La tolérance zéro",
      "La liberté de culte",
      "La religion d'État",
      "La laïcité qui restreint toute pratique religieuse",
    ],
    answer_index: 1,
    answer: "La liberté de culte",
  },
  {
    id: 112,
    topic: "Institutions",
    question: "Qui préside l'Assemblée nationale lors des séances ?",
    choices: [
      "Le Président de la République",
      "Le Président de l'Assemblée nationale",
      "Le Premier ministre",
      "Le président du Sénat",
    ],
    answer_index: 1,
    answer: "Le Président de l'Assemblée nationale",
  },
  {
    id: 113,
    topic: "Politique",
    question: "Qu'est-ce que la décentralisation ?",
    choices: [
      "La concentration des pouvoirs à Paris",
      "La redistribution des pouvoirs vers les collectivités locales",
      "La suppression des régions",
      "L'élection du Président par les maires",
    ],
    answer_index: 1,
    answer: "La redistribution des pouvoirs vers les collectivités locales",
  },
  {
    id: 114,
    topic: "Géographie",
    question:
      "Quelle ville française est célèbre pour le festival international du film chaque année ?",
    choices: ["Cannes", "Clermont-Ferrand", "Angoulême", "Deauville"],
    answer_index: 0,
    answer: "Cannes",
  },
  {
    id: 115,
    topic: "Culture",
    question: "Quel roman de Marcel Proust est le plus célèbre ?",
    choices: [
      "À la recherche du temps perdu",
      "Les Rougon-Macquart",
      "Le Père Goriot",
      "Germinal",
    ],
    answer_index: 0,
    answer: "À la recherche du temps perdu",
  },
  {
    id: 116,
    topic: "Patrimoine",
    question:
      "Quel site préhistorique célèbre se situe en Dordogne et comporte des peintures rupestres ?",
    choices: ["Lascaux", "Grotte Chauvet", "Altamira", "Grottes d'Ajanta"],
    answer_index: 0,
    answer: "Lascaux",
  },
  {
    id: 117,
    topic: "Histoire",
    question:
      "Quel parlement médiéval consultatif se réunissait parfois pour conseiller le roi ?",
    choices: [
      "Les États généraux",
      "Le Sénat",
      "L'Assemblée nationale",
      "Le Parlement européen",
    ],
    answer_index: 0,
    answer: "Les États généraux",
  },
  {
    id: 118,
    topic: "Valeurs républicaines",
    question:
      "Quel principe implique la séparation des pouvoirs (exécutif, législatif, judiciaire) ?",
    choices: [
      "La souveraineté nationale",
      "La séparation des pouvoirs",
      "La centralisation",
      "La monarchie",
    ],
    answer_index: 1,
    answer: "La séparation des pouvoirs",
  },
  {
    id: 119,
    topic: "Institutions",
    question: "Quel est le rôle du Sénat ?",
    choices: [
      "Gérer les finances régionales",
      "Représenter les collectivités territoriales et voter les lois",
      "Nommer le Président",
      "Contrôler l'armée",
    ],
    answer_index: 1,
    answer: "Représenter les collectivités territoriales et voter les lois",
  },
  {
    id: 120,
    topic: "Géographie",
    question:
      "Quelle ville est connue comme la capitale gastronomique et historique du sud-ouest (foie gras, vin) ?",
    choices: ["Lille", "Toulouse", "Bordeaux", "Biarritz"],
    answer_index: 2,
    answer: "Bordeaux",
  },
];
